export const iconsCategoriesMock = [
  {
    _id: "62363d7fbad2a536854d0824",
    category: "alphabet",
    icons: [
      "a",
      "b",
      "c",
      "d",
      "e",
      "f",
      "g",
      "h",
      "i",
      "j",
      "k",
      "l",
    ],
  },
  {
    _id: "62363dacbad2a536854d0825",
    category: "animals",
    icons: [
      "bugs",
      "cat",
      "cow",
      "crow",
      "dog",
      "dove",
      "dragon",
      "fish",
      "frog",
      "hippo",
      "horse",
      "spider",
      "paw",
    ],
  },
  {
    _id: "62363dc1bad2a536854d0826",
    category: "astronomy",
    icons: [
      "globe",
      "meteor",
      "moon",
      "satellite",
      "satellite-dish",
      "shuttle-space",
      "user-astronaut",
    ],
  },
  {
    _id: "62363dd0bad2a536854d0827",
    category: "automative",
    icons: [
      "bus",
      "car",
      "car-burst",
      "charging-station",
      "gas-pump",
      "motorcycle",
      "truck",
      "taxi",
      "truck-medical",
    ],
  },
  {
    _id: "62363de4bad2a536854d0828",
    category: "buildings",
    icons: [
      "archway",
      "building",
      "building-columns",
      "campground",
      "church",
      "city",
      "dungeon",
      "hospital",
      "house",
      "igloo",
      "shop",
      "vihara",
    ],
  },
];
